# Generated by Django 4.0.6 on 2022-08-16 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='syntaxeme',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='wordform',
            name='ID',
        ),
        migrations.DeleteModel(
            name='Clause',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Sentence',
        ),
        migrations.DeleteModel(
            name='Syntaxeme',
        ),
        migrations.DeleteModel(
            name='Wordform',
        ),
    ]
