# Generated by Django 4.0.6 on 2022-08-11 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0002_sentence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('sentence_ID', models.CharField(max_length=50)),
                ('frame_ID', models.CharField(max_length=50)),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.sentence')),
            ],
        ),
        migrations.CreateModel(
            name='Syntaxeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_ID', models.CharField(max_length=50)),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.clause')),
            ],
        ),
        migrations.CreateModel(
            name='Wordform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syntaxeme_ID', models.CharField(max_length=50)),
                ('frame_role_ID', models.CharField(max_length=50)),
                ('position_in_document', models.CharField(max_length=50)),
                ('position_in_sentence', models.CharField(max_length=50)),
                ('clause_position', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=50)),
                ('root_morpheme_ID', models.CharField(max_length=50)),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.syntaxeme')),
            ],
        ),
    ]
