# Generated by Django 4.0 on 2022-04-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_alter_sentence_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='text',
            field=models.CharField(max_length=3000),
        ),
    ]
